cabal-version:      2.4
name:               effective-curry-interpreter
version:            0.1.0.0

author:             Niels Bunkenburg
maintainer:         nbu@informatik.uni-kiel.de

data-files: Prelude.curry
data-dir: data

library
    other-modules: Free
                   , Type
                   , Transformation.FCY2AE
                   , Effect.FlatCurry.Constructor
                   , Effect.FlatCurry.Function
                   , Effect.FlatCurry.Let
                   , Effect.General.ND
                   , Paths_effective_curry_interpreter
                   , Effect.General.Memoization
                   , Effect.General.State
                   , Effect.General.Reader
                   , Effect.FlatCurry.Declarations
                   , Effect.FlatCurry.IO
                   , Effect.General.Error
                   , Debug
                   , Data.Union
                   , Signature
                   , Monolith
                   , InterpFL
                   
    exposed-modules: App, Pipeline
    build-depends:    
      , base
      , curry-frontend ^>=3.0.0
      , containers
      , mtl
      , filepath
      , htrace
      , directory
      , random
      , clock
      , ghc
      , unordered-containers
      , primitive
    hs-source-dirs:   src
    default-language: Haskell2010
    default-extensions: StrictData
    ghc-options: -Wall -O2  -fprof-late-overloaded-calls -finfo-table-map  -fdistinct-constructor-tables

executable efci
  hs-source-dirs:   app
  main-is:          Main.hs
  default-language: Haskell2010
  ghc-options:      -O2 -fprof-late-overloaded-calls -threaded -rtsopts
  build-depends:
      base
    , effective-curry-interpreter

test-suite tests
      default-language      : Haskell2010
      type                  : exitcode-stdio-1.0
      hs-source-dirs        : tests
      main-is               : Main.hs
      ghc-options           : -Wall -O2
      build-depends         : base
                            , hspec
                            , HUnit
                            , effective-curry-interpreter
                            , curry-frontend
                            , directory
                            , silently

benchmark benchmark-prac-haskell-bench
  type:           exitcode-stdio-1.0
  hs-source-dirs: benchmarks
  main-is:        Main.hs
  ghc-options:    -O2 -fspecialise -fcross-module-specialise -flate-specialise -threaded
  build-depends:  base
                , criterion
                , effective-curry-interpreter
                , curry-frontend
                , directory
                , process
